/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package projetosz.swing;

import javax.swing.JOptionPane;

/**
 *
 * @author sergio.9909
 */
public class calc extends javax.swing.JDialog {

    /**
     * Creates new form calc
     */
    public calc(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCientifica = new javax.swing.JButton();
        jButtonZero = new javax.swing.JButton();
        jButtonSete = new javax.swing.JButton();
        jButtonOito = new javax.swing.JButton();
        jButtonNove = new javax.swing.JButton();
        jButtonSeis = new javax.swing.JButton();
        jButtonQuatro = new javax.swing.JButton();
        jButtonCinco = new javax.swing.JButton();
        jButtonDois = new javax.swing.JButton();
        jButtonTres = new javax.swing.JButton();
        jButtonUm = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonSubtracao = new javax.swing.JButton();
        jButtonMultiplicacao = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButtonDivisao = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonVirgula = new javax.swing.JButton();
        jButtonPonto = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 94, 94));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculadora"));
        jPanel1.setForeground(new java.awt.Color(79, 79, 79));

        jButtonCientifica.setBackground(new java.awt.Color(98, 98, 98));
        jButtonCientifica.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButtonCientifica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCientifica.setText("Calculadora Cientifica");
        jButtonCientifica.setMargin(new java.awt.Insets(1, 10, 1, 10));
        jButtonCientifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCientificaActionPerformed(evt);
            }
        });

        jButtonZero.setBackground(new java.awt.Color(98, 98, 98));
        jButtonZero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonZero.setForeground(new java.awt.Color(255, 255, 255));
        jButtonZero.setText("0");
        jButtonZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZeroActionPerformed(evt);
            }
        });

        jButtonSete.setBackground(new java.awt.Color(98, 98, 98));
        jButtonSete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSete.setText("7");
        jButtonSete.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeteActionPerformed(evt);
            }
        });

        jButtonOito.setBackground(new java.awt.Color(98, 98, 98));
        jButtonOito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonOito.setForeground(new java.awt.Color(255, 255, 255));
        jButtonOito.setText("8");
        jButtonOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOitoActionPerformed(evt);
            }
        });

        jButtonNove.setBackground(new java.awt.Color(98, 98, 98));
        jButtonNove.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonNove.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNove.setText("9");
        jButtonNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNoveActionPerformed(evt);
            }
        });

        jButtonSeis.setBackground(new java.awt.Color(98, 98, 98));
        jButtonSeis.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSeis.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSeis.setText("6");
        jButtonSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeisActionPerformed(evt);
            }
        });

        jButtonQuatro.setBackground(new java.awt.Color(98, 98, 98));
        jButtonQuatro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonQuatro.setForeground(new java.awt.Color(255, 255, 255));
        jButtonQuatro.setText("4");
        jButtonQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuatroActionPerformed(evt);
            }
        });

        jButtonCinco.setBackground(new java.awt.Color(98, 98, 98));
        jButtonCinco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonCinco.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCinco.setText("5");
        jButtonCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCincoActionPerformed(evt);
            }
        });

        jButtonDois.setBackground(new java.awt.Color(98, 98, 98));
        jButtonDois.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonDois.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDois.setText("2");
        jButtonDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoisActionPerformed(evt);
            }
        });

        jButtonTres.setBackground(new java.awt.Color(98, 98, 98));
        jButtonTres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonTres.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTres.setText("3");
        jButtonTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTresActionPerformed(evt);
            }
        });

        jButtonUm.setBackground(new java.awt.Color(98, 98, 98));
        jButtonUm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonUm.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUm.setText("1");
        jButtonUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUmActionPerformed(evt);
            }
        });

        jButtonIgual.setBackground(new java.awt.Color(98, 98, 98));
        jButtonIgual.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonIgual.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIgual.setText("=");

        jButtonSubtracao.setBackground(new java.awt.Color(98, 98, 98));
        jButtonSubtracao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSubtracao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubtracao.setText("-");
        jButtonSubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtracaoActionPerformed(evt);
            }
        });

        jButtonMultiplicacao.setBackground(new java.awt.Color(98, 98, 98));
        jButtonMultiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonMultiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMultiplicacao.setText("X");
        jButtonMultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacaoActionPerformed(evt);
            }
        });

        jButtonSoma.setBackground(new java.awt.Color(98, 98, 98));
        jButtonSoma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonSoma.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSoma.setText("+");
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });

        jButtonDivisao.setBackground(new java.awt.Color(98, 98, 98));
        jButtonDivisao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDivisao.setText("/");
        jButtonDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivisaoActionPerformed(evt);
            }
        });

        jButtonC.setBackground(new java.awt.Color(98, 98, 98));
        jButtonC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonC.setForeground(new java.awt.Color(255, 255, 255));
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonVirgula.setBackground(new java.awt.Color(98, 98, 98));
        jButtonVirgula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonVirgula.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVirgula.setText(",");
        jButtonVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVirgulaActionPerformed(evt);
            }
        });

        jButtonPonto.setBackground(new java.awt.Color(98, 98, 98));
        jButtonPonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButtonPonto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonPonto.setText(".");

        jTextFieldResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonDois, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonSete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonOito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButtonCientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonNove, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldResultado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDivisao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonC, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(jTextFieldResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTres, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDois, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonUm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonQuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCinco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSeis, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMultiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonOito, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNove, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVirgula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonZero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCientifica, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUmActionPerformed
       int um = 1; 
       String um1 = String.valueOf(um);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + um1);
       } else {
       jTextFieldResultado.setText(um1);
       }
    }//GEN-LAST:event_jButtonUmActionPerformed

    private void jTextFieldResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldResultadoActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        jTextFieldResultado.setText("");
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoisActionPerformed
               int dois = 2; 
       String dois2 = String.valueOf(dois);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + dois2);
       } else {
       jTextFieldResultado.setText(dois2);
    }
    }//GEN-LAST:event_jButtonDoisActionPerformed

    private void jButtonTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTresActionPerformed
               int tres = 3; 
       String tres3 = String.valueOf(tres);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + tres3);
       } else {
       jTextFieldResultado.setText(tres3);
    }
    }//GEN-LAST:event_jButtonTresActionPerformed

    private void jButtonQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuatroActionPerformed
               int quatro = 4; 
       String quatro4 = String.valueOf(quatro);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + quatro4);
       } else {
       jTextFieldResultado.setText(quatro4);
    }
    }//GEN-LAST:event_jButtonQuatroActionPerformed

    private void jButtonCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCincoActionPerformed
                       int cinco = 5; 
       String cinco5 = String.valueOf(cinco);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + cinco5);
       } else {
       jTextFieldResultado.setText(cinco5);
    }
    }//GEN-LAST:event_jButtonCincoActionPerformed

    private void jButtonSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeisActionPerformed
                       int seis = 6; 
       String seis6 = String.valueOf(seis);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + seis6);
       } else {
       jTextFieldResultado.setText(seis6);
    }
    }//GEN-LAST:event_jButtonSeisActionPerformed

    private void jButtonSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeteActionPerformed
                       int sete = 7; 
       String sete7 = String.valueOf(sete);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + sete7);
       } else {
       jTextFieldResultado.setText(sete7);
    }
    }//GEN-LAST:event_jButtonSeteActionPerformed

    private void jButtonOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOitoActionPerformed
                       int oito = 8; 
       String oito8 = String.valueOf(oito);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + oito8);
       } else {
       jTextFieldResultado.setText(oito8);
    }
    }//GEN-LAST:event_jButtonOitoActionPerformed

    private void jButtonNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNoveActionPerformed
                       int nove = 9; 
       String nove9 = String.valueOf(nove);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + nove9);
       } else {
       jTextFieldResultado.setText(nove9);
    }      
    }//GEN-LAST:event_jButtonNoveActionPerformed

    private void jButtonCientificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCientificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCientificaActionPerformed

    private void jButtonZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZeroActionPerformed
                               int zero = 0; 
       String zero0 = String.valueOf(zero);
       
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + zero0);
       } else {
       jTextFieldResultado.setText(zero0);
    } 
    }//GEN-LAST:event_jButtonZeroActionPerformed

    private void jButtonVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVirgulaActionPerformed
       if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + ",");
       } 
    }//GEN-LAST:event_jButtonVirgulaActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
       String mais = " + ";        
        if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + mais);
       } else {
       jTextFieldResultado.setText(mais);
    } 

    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonSubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtracaoActionPerformed
        String menos = " - ";        
        if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + menos);
       } else {
       jTextFieldResultado.setText(menos);
    }//GEN-LAST:event_jButtonSubtracaoActionPerformed
    }
    private void jButtonMultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacaoActionPerformed
        String vezes = " x ";        
        if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + vezes);
       } else {
       jTextFieldResultado.setText(vezes);
    }//GEN-LAST:event_jButtonMultiplicacaoActionPerformed
    }
    private void jButtonDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivisaoActionPerformed
      String divide = " / ";        
        if (!"".equals(jTextFieldResultado.getText())){
         jTextFieldResultado.setText(jTextFieldResultado.getText() + divide);
       } else {
       jTextFieldResultado.setText(divide);
    }   
    }//GEN-LAST:event_jButtonDivisaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                calc dialog = new calc(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCientifica;
    private javax.swing.JButton jButtonCinco;
    private javax.swing.JButton jButtonDivisao;
    private javax.swing.JButton jButtonDois;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonMultiplicacao;
    private javax.swing.JButton jButtonNove;
    private javax.swing.JButton jButtonOito;
    private javax.swing.JButton jButtonPonto;
    private javax.swing.JButton jButtonQuatro;
    private javax.swing.JButton jButtonSeis;
    private javax.swing.JButton jButtonSete;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSubtracao;
    private javax.swing.JButton jButtonTres;
    private javax.swing.JButton jButtonUm;
    private javax.swing.JButton jButtonVirgula;
    private javax.swing.JButton jButtonZero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldResultado;
    // End of variables declaration//GEN-END:variables
}
